apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: farskapsportal
  labels:
    team: farskapsportal
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
        - id: secure_logs
  azure:
    application:
      allowAllUsers: true
      enabled: true
  tokenx:
    enabled: true
  image: {{ image }}
  kafka:
    pool: nav-dev
  liveness:
    path: /internal/actuator/health
    initialDelay: 130
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 130
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  replicas:
    max: {{ replicas }}
    min: {{ replicas }}
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  secureLogs:
    enabled: true
  ingresses:
    - {{ ingress }}
  env:
    - name: APPNAVN
      value: {{ name }}
    - name: SPRING_PROFILES_ACTIVE
      value: live, nais
  {{#each env}}
    - name: {{this.name}}
      value: "{{this.value}}"
  {{/each}}
  gcp:
    buckets:
      - name: {{ name }}-dev-pades
        lifecycleCondition:
          age: 7
          createdBefore: 2023-01-01
          numNewerVersions: 1
          withState: ANY
      - name: {{ name }}-dev-xades
        lifecycleCondition:
          age: 7
          createdBefore: 2023-01-01
          numNewerVersions: 1
          withState: ANY
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
    sqlInstances:
      - name: {{ gcp.sql-instances.name }}
        tier: {{ gcp.sql-instances.tier }}
        type: {{ gcp.sql-instances.type }}
        databases:
          - name: {{ gcp.sql-instances.databases.name }}
            envVarPrefix: {{ gcp.sql-instances.databases.env-var-prefix }}
        flags:
          - name: autovacuum
            value: "on"
  accessPolicy:
    inbound:
      rules:
        - application: farskapsportal-ui
        - application: farskapsportal-ui-feature
        - application: statuspoll
          namespace: navdig
          cluster: dev-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: api.difitest.signering.posten.no
        - host: folkeregisteret-api-ekstern.sits.no
        - host: secretmanager.googleapis.com
        - host: oppgave.dev-fss-pub.nais.io
