apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: farskapsportal
  labels:
    team: farskapsportal
spec:
  azure:
    application:
      allowAllUsers: true
      enabled: true
  tokenx:
    enabled: true
  image: {{ image }}
  kafka:
    pool: nav-prod
  liveness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  secureLogs:
    enabled: true
  ingresses:
    - {{ ingress }}
  env:
    - name: APPNAVN
      value: {{ name }}
    - name: SPRING_PROFILES_ACTIVE
      value: live, nais
  {{#each env}}
    - name: {{this.name}}
      value: "{{this.value}}"
  {{/each}}
  gcp:
    buckets:
      - name: {{ name }}-pades
        retentionPeriodDays: 365
        lifecycleCondition:
          age: 365
          createdBefore: 2022-01-01
          numNewerVersions: 1
          withState: ANY
      - name: {{ name }}-xades
        retentionPeriodDays: 365
        lifecycleCondition:
          age: 365
          createdBefore: 2022-01-01
          numNewerVersions: 1
          withState: ANY
    sqlInstances:
      - diskSize: {{ gcp.sql-instances.diskSize }}
        name: {{ gcp.sql-instances.name }}
        tier: {{ gcp.sql-instances.tier }}
        type: {{ gcp.sql-instances.type }}
        databases:
          - name: {{ gcp.sql-instances.databases.name }}
            envVarPrefix: {{ gcp.sql-instances.databases.env-var-prefix }}
        flags:
          - name: autovacuum
            value: "on"
  accessPolicy:
    inbound:
      rules:
        - application: farskapsportal-ui
        - application: statuspoll
          namespace: navdig
          cluster: prod-gcp
    outbound:
      external:
        - host: api-gw.oera.no
        - host: api.signering.posten.no
        - host: folkeregisteret.api.skatteetaten.no
        - host: secretmanager.googleapis.com
        - host: oppgave.prod-fss-pub.nais.io
  webproxy: true