-- Table: dokument

-- DROP TABLE dokument;

CREATE TABLE dokument
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dokument_status_url bytea,
    dokumentnavn character varying(255) COLLATE pg_catalog."default",
    innhold bytea,
    pades_url bytea,
    redirect_url_far bytea,
    redirect_url_mor bytea,
    signert_av_far timestamp without time zone,
    signert_av_mor timestamp without time zone,
    CONSTRAINT dokument_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;