-- Table: farskapsportal.barn

-- DROP TABLE farskapsportal.barn;

CREATE TABLE farskapsportal.barn
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    foedselsnummer character varying(255) COLLATE pg_catalog."default",
    termindato date,
    CONSTRAINT barn_pkey PRIMARY KEY (id),
    CONSTRAINT uk_barn_foedselsnummer UNIQUE (foedselsnummer)
)

    TABLESPACE pg_default;

ALTER TABLE farskapsportal.barn
    OWNER to farskapsportal_api;