CREATE TABLE test
(

    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1000000 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    etternavn character varying(255) COLLATE pg_catalog."default"
)

    TABLESPACE pg_default;