-- Table: forelder

-- DROP TABLE forelder;

CREATE TABLE forelder
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    etternavn character varying(255) COLLATE pg_catalog."default",
    foedselsnummer character varying(255) COLLATE pg_catalog."default",
    fornavn character varying(255) COLLATE pg_catalog."default",
    mellomnavn character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT forelder_pkey PRIMARY KEY (id),
    CONSTRAINT uk_forelder_foedselsnummer UNIQUE (foedselsnummer)
)

    TABLESPACE pg_default;

ALTER TABLE forelder
    OWNER to farskapsportal_api;