-- Table: farskapserklaering

-- DROP TABLE farskapserklaering;

CREATE TABLE farskapserklaering
(

    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1000000 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    barn_id integer,
    dokument_id integer,
    far_id integer,
    mor_id integer,
    CONSTRAINT farskapserklaering_pkey PRIMARY KEY (id),
    CONSTRAINT fk_barn_id FOREIGN KEY (barn_id)
        REFERENCES barn (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_forelder_mor_id FOREIGN KEY (mor_id)
        REFERENCES forelder (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_dokument_id FOREIGN KEY (dokument_id)
        REFERENCES dokument (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_forelder_far_id FOREIGN KEY (far_id)
        REFERENCES forelder (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;