-- Table: public.status_kontrollere_far

-- DROP TABLE public.status_kontrollere_far;

CREATE TABLE public.status_kontrollere_far
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    mor_id integer NOT NULL,
    antall_feilede_forsoek integer NOT NULL default 0,
    tidspunkt_siste_feilede_forsoek timestamp without time zone,
    CONSTRAINT status_kontrollere_far_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

GRANT ALL ON TABLE public.status_kontrollere_far TO cloudsqliamuser;