-- Table: public.signeringsinformasjon

-- DROP TABLE public.signeringsinformasjon;

CREATE TABLE public.signeringsinformasjon
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    signeringstidspunkt timestamp without time zone,
    redirect_url varchar(255),
    status_url varchar(255),
    undertegner_url varchar(255),
    CONSTRAINT signeringsinformasjon_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

GRANT ALL ON TABLE public.signeringsinformasjon TO cloudsqliamuser;