-- Table: meldingslogg

/*
    DROP TABLE public.meldingslogg;
 */

CREATE TABLE public.meldingslogg(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
<<<<<<< HEAD
    tidspunktForOversendelse timestamp without time zone,
    meldingsidSkatt varchar(255),
=======
    tidspunkt_for_oversendelse timestamp without time zone,
    meldingsid_skatt varchar(255),
>>>>>>> main
    CONSTRAINT meldingslogg_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;
