-- Table: meldingslogg

/*
    DROP TABLE public.meldingslogg;
 */

CREATE TABLE public.meldingslogg(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    tidspunktForOversendelse timestamp without time zone,
    meldingsidSkatt bigint,
    CONSTRAINT meldingslogg_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;
