schema: pdl-api-schema.graphql
extensions:
  endpoints:
    PDL GraphQL Endpoint:
      url: https://pdl-api.nais.preprod.local/graphql
      headers:
        user-agent: farskapsportal-api
      introspect: false
