name: asynkron
ingress: https://farskapsportal-asynkron.intern.nav.no
kafka:
  schema-registry:
    host: kafka-schema-registry.nais.adeo.no
env:
  - name: ARKIVERINGSINTERVALL
    value: 3600000
  - name: ARKIVERINGSFORSINKELSE
    value: 60000
  - name: APIGW_URL
    value: https://api-gw.oera.no
  - name: BRUKERNOTIFIKASJON_PAA
    value: "true"
  - name: DB_NAME
    value: fpdb-prod
  - name: DEAKTIVERINGSRATE
    value: "0 30 13 * * ?"
  - name: VIRKSOMHETSSERTIFIKAT_PROSJEKT_ID
    value: "642182003125"
  - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_NAVN
    value: virksomhetssertifikat-farskap-keystore-jceks_2021-2024
  - name: VIRKSOMHETSSERTIFIKAT_HEMMELIGHET_VERSJON
    value: "3"
  - name: VIRKSOMHETSSERTIFIKAT_PASSORD_PROSJEKT_ID
    value: "642182003125"
  - name: VIRKSOMHETSSERTIFIKAT_PASSORD_HEMMELIGHET_NAVN
    value: farskap-keystore-credentials-json
  - name: VIRKSOMHETSSERTIFIKAT_PASSORD_HEMMELIGHET_VERSJON
    value: "3"
  - name: FARSKAPSPORTAL_API_SCOPE
    value: prod-gcp.farskapsportal.api
  - name: FARSKAPSPORTAL_URL
    value: https://farskapsportal.nav.no
  - name: FARSKAPSPORTAL_API_URL
    value: http://farskapsportal-api.farskapsportal.svc.cluster.local
  - name: OPPGAVEAPI_URL
    value: https://oppgave.nais.adeo.no/api/v1/oppgaver
  - name: OPPGAVE_SCOPE
    value: prod-fss.oppgavehandtering.oppgave
  - name: INTEGRATION_TEST_CONTROLLER_PAA
    value: "false"
  - name: POSTGRES_CONNECTION_NAME
    value: farskapsportal-prod-f231:europe-north1:fp-prod
  - name: POSTGRES_USER_NAME
    value: asynkron_prod
  - name: SKATT_URL
    value: https://folkeregisteret.api.skatteetaten.no
  - name: OPPGAVESTYRINGSINTERVALL
    value: "0 0 7 * * ?"
  - name: OPPGAVESTYRINGSFORSINKELSE
    value: 1
  - name: VARSLE_OM_UFERDIG_ERKLAERING_CRON
    value: "0 0 14 ? * TUE"
  - name: VURDERE_OPPGAVE_INTERVALL
    value: "0 0 8 ? * 1-5"
secret:
  - name: farskapsportal-api-secret
  - name: postgres-user-asynkron-prod-password
